export type CountryPhoto = { url: string; alt: string; caption: string };
export const countryPhotos: Record<string, CountryPhoto[]> = {
  BG: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3rbJCtPxlY6aKF0yztOW9Tdq5XjZNAxmrhb3S", alt: "bulgaria1-4", caption: "bulgaria1-4.jpg" },
  ],
  GE: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3JaUtRZGaqA6yd1xC9XjpFZcYkSQVHPsmRBKr", alt: "georgia1-2", caption: "georgia1-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3LD2qblBiU8M0pRYoQvfnu9IkVBxt3X6l1z7G", alt: "georgia3-3", caption: "georgia3-3.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3nbFvbBpyDqL0mEl3waKSdVgzkryN6boxpOYC", alt: "georgia3-1", caption: "georgia3-1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3BmDNHBZzmu5QoLhRsYHFnkxwIGc9X8bV6NEZ", alt: "georgia3-4", caption: "georgia3-4.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3zS7UEUMKriMfETts6D5wUvjaNSqyXFCzOokb", alt: "georgia3-2", caption: "georgia3-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG34RusHzLmB9hKrkJLWnxjT51C6UEs3aqvbwAD", alt: "georgia2-2", caption: "georgia2-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3akTVCY0XnVCh9pYMZgPm2qu36IxctT48dsej", alt: "Random photos from Tbilisi, autumn 2022.", caption: "Random photos from Tbilisi, autumn 2022.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3V6AwnWlZkmFIlC3PAKT2b5GLpBe9QgtyzYhR", alt: "More random stuff from Tbilisi, spring 2023.", caption: "More random stuff from Tbilisi, spring 2023.jpg" },
  ],
  ID: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3KdcKYBqthe0UiCV4knWRMfrTLZqA25JpKoyG", alt: "indonesia1-2", caption: "indonesia1-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3JU8jxWdGaqA6yd1xC9XjpFZcYkSQVHPsmRBK", alt: "indonesia1-1", caption: "indonesia1-1.jpg" },
  ],
  IN: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3Etfhm2JHNkV5QqA0PzHX9LgOUocZvywRm73n", alt: "india1-1", caption: "india1-1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3Teglq65EBwKnHCMpi8fIPUDYxNvSVbOayAtj", alt: "india1-3", caption: "india1-3.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3ruchc2kxlY6aKF0yztOW9Tdq5XjZNAxmrhb3", alt: "india1-2", caption: "india1-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3P5q46HbAh0sgMwWZ8lGvY1LKQkfy4bdJEe6n", alt: "Taj Mahal, Agra, India, September 2023", caption: "Taj Mahal, Agra, India, September 2023.webp" },
  ],
  KZ: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG36GpPiZkUv4opVJsaElCQZPDTAOkq5rGYd3uj", alt: "kazakhstan1-4", caption: "kazakhstan1-4.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3rnYdycxlY6aKF0yztOW9Tdq5XjZNAxmrhb3S", alt: "kazakhstan1-6", caption: "kazakhstan1-6.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3B23NIyzmu5QoLhRsYHFnkxwIGc9X8bV6NEZO", alt: "kazakhstan1-2", caption: "kazakhstan1-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3ogJuKMX3YAux1Get6gWhcUZ27b4H9smXl0zP", alt: "kazakhstan1-3", caption: "kazakhstan1-3.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3hGpS0GEu7AbEPfIcJgpTQLjeq2woXd06FB3W", alt: "kazakhstan1-5", caption: "kazakhstan1-5.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3zFgi2kZMKriMfETts6D5wUvjaNSqyXFCzOok", alt: "kazakhstan1-1", caption: "kazakhstan1-1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3xRaZat9iXQu6CW0bOrM4LHdzBhwEPo7t93jI", alt: "Ile-Alatau National Park, Almaty, Kazakhstan, pt.2, July 2023.", caption: "Ile-Alatau National Park, Almaty, Kazakhstan, pt.2, July 2023.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3aXZz39o0XnVCh9pYMZgPm2qu36IxctT48dse", alt: "Ascension Cathedral, Almaty, Kazakhstan, July 2023.", caption: "Ascension Cathedral, Almaty, Kazakhstan, July 2023.jpg" },
  ],
  ME: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3w9LVif6rUvIGfKnA1XTJHuF8V4M73yq2ciOD", alt: "montenegro1-1", caption: "montenegro1-1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3RcOAZpKPwcXvqaS14sbx306iCEpYL5hGZoTe", alt: "montenegro1-2", caption: "montenegro1-2.jpg" },
  ],
  MK: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3goHPUcVLjUb4pJ3ZID8lCsNxE01vKB6QtPhy", alt: "north-macedonia1-3", caption: "north-macedonia1-3.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3X5jNY7eT9ul3GraZ6FegdonvOWzwUsiDImJR", alt: "north-macedonia1-1", caption: "north-macedonia1-1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3ogluIdsX3YAux1Get6gWhcUZ27b4H9smXl0z", alt: "north-macedonia1-4", caption: "north-macedonia1-4.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3JVqOPqGaqA6yd1xC9XjpFZcYkSQVHPsmRBKr", alt: "north-macedonia1-2", caption: "north-macedonia1-2.jpg" },
  ],
  MY: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3oQLaGcX3YAux1Get6gWhcUZ27b4H9smXl0zP", alt: "malaysia1-2", caption: "malaysia1-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG35rur9XczSAQbdnUX8ZMxtDgKcq6JL9eNljIp", alt: "malaysia1-4", caption: "malaysia1-4.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG34AH7s7LmB9hKrkJLWnxjT51C6UEs3aqvbwAD", alt: "malaysia1-5", caption: "malaysia1-5.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG35wGkxZOczSAQbdnUX8ZMxtDgKcq6JL9eNljI", alt: "malaysia1-3", caption: "malaysia1-3.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3bDZRCWp1BTwEcQazgqlhy09tukiKWNVIHUfo", alt: "malaysia1-1", caption: "malaysia1-1.jpg" },
  ],
  PH: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3WzmNhSrutUqhLGv6nJOMIYHT8jmxsXc5fZzA", alt: "philippines1-1", caption: "philippines1-1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3zQF1GTMKriMfETts6D5wUvjaNSqyXFCzOokb", alt: "philippines1-3", caption: "philippines1-3.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3bQBQ6Dp1BTwEcQazgqlhy09tukiKWNVIHUfo", alt: "philippines1-4", caption: "philippines1-4.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3KhUJecqthe0UiCV4knWRMfrTLZqA25JpKoyG", alt: "philippines1-2", caption: "philippines1-2.jpg" },
  ],
  RS: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3eOJn4vgubh5xzFZykS1Wmrqcv6N8w7oDIGMQ", alt: "serbia1-4", caption: "serbia1-4.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3E2TOdaHNkV5QqA0PzHX9LgOUocZvywRm73ns", alt: "serbia1-3", caption: "serbia1-3.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3zqZSieMKriMfETts6D5wUvjaNSqyXFCzOokb", alt: "serbia1", caption: "serbia1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3xLVTv59iXQu6CW0bOrM4LHdzBhwEPo7t93jI", alt: "serbia1-2", caption: "serbia1-2.jpg" },
  ],
  RU: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3GgNya4Qgi9Tn8CRmkPrVejASwKv417Hol2d3", alt: "russia1-3", caption: "russia1-3.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3YWvRoy7du6RwFNDQMikvVWsehJjqB1p80rGK", alt: "russia1-7", caption: "russia1-7.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3OyyzbOOfvR7nUxBZ3H9EWwyYpOi6TVzILraS", alt: "russia1-4", caption: "russia1-4.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3n09JReyDqL0mEl3waKSdVgzkryN6boxpOYCI", alt: "russia1-2", caption: "russia1-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3bLFXE9bp1BTwEcQazgqlhy09tukiKWNVIHUf", alt: "russia1-6", caption: "russia1-6.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3obn37AX3YAux1Get6gWhcUZ27b4H9smXl0zP", alt: "russia1-1", caption: "russia1-1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3JrEJu0GaqA6yd1xC9XjpFZcYkSQVHPsmRBKr", alt: "from-russia-with-love", caption: "from-russia-with-love.jpg" },
  ],
  TH: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG39Yx779uDKWXljPx8VhARpvuGIZm2YyM5rz0b", alt: "thailand1-1", caption: "thailand1-1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3IMWx4BYK9zmEePfVRcdC2ybUSZ6isYFWAaL7", alt: "thailand1-4", caption: "thailand1-4.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3BNBNGHzmu5QoLhRsYHFnkxwIGc9X8bV6NEZO", alt: "thailand1-5", caption: "thailand1-5.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3FTZnF1aUXinLRQA83HWGzxDZfgObytohp2IB", alt: "thailand1-3", caption: "thailand1-3.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3XcpVHReT9ul3GraZ6FegdonvOWzwUsiDImJR", alt: "thailand1-2", caption: "thailand1-2.jpg" },
  ],
  TR: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3fH5KRgnsXjHSoJPdT5KWvRL2i6ElnqD0aebB", alt: "turkey2-4", caption: "turkey2-4.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3kH8KMFChBM8X02faJLycrPl96tqbSKuWID4h", alt: "turkey2", caption: "turkey2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3xs6wHI9iXQu6CW0bOrM4LHdzBhwEPo7t93jI", alt: "turkey4-7", caption: "turkey4-7.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3p267eT4uGR1EnsDICWdxiXf0QlZ4z8tHLV9O", alt: "turkey4-5", caption: "turkey4-5.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3NrTTsXJWMY7beRzp9AvONU5ZCHyarQwdu216", alt: "turkey3-1", caption: "turkey3-1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3nosqBayDqL0mEl3waKSdVgzkryN6boxpOYCI", alt: "turkey2-2", caption: "turkey2-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3BJT8YSzmu5QoLhRsYHFnkxwIGc9X8bV6NEZO", alt: "turkey4-2", caption: "turkey4-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG31VefBLtoefd4BhzY095VGLwyiJxagQs2WcMR", alt: "turkey2-1", caption: "turkey2-1.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3WxxJ3y6SrutUqhLGv6nJOMIYHT8jmxsXc5fZ", alt: "turkey1-2", caption: "turkey1-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG37y9tEbTUD291dxHcjwO84hoEGMgPau5nNKzB", alt: "erdek-cutie", caption: "erdek-cutie.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3kvsUU7hBM8X02faJLycrPl96tqbSKuWID4hv", alt: "erdek-cutie", caption: "erdek-cutie.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3Lao1MfBiU8M0pRYoQvfnu9IkVBxt3X6l1z7G", alt: "Trip to Erdek, pt.1, August 2023.", caption: "Trip to Erdek, pt.1, August 2023.jpg" },
  ],
  UZ: [
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG30MEU29oJFXpIgM9Bizc72HLGDwQCf8mKNEn0", alt: "uzbekistan1-2", caption: "uzbekistan1-2.jpg" },
    { url: "https://mr4v9rgsnq.ufs.sh/f/jf84pSwRMaG3XVWTK4KeT9ul3GraZ6FegdonvOWzwUsiDImJ", alt: "Magic City Park and random photos from Tashkent, Uzbekistan, June 2023.", caption: "Magic City Park and random photos from Tashkent, Uzbekistan, June 2023.jpg" },
  ],
};